[package]
name = "stijn-gamettwee/classes"
description = "A professional class framework for Roblox Luau inspired by C++ architecture. Supports constructors, inheritance, extensible services, and clean OOP workflows for large-scale Roblox projects."
version = "0.0.1"
license = "Apache-2.0"
authors = ["stijn_gamet"]
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/stijn-gametTwee/Classes"
homepage = "https://stijn-gamettwee.github.io/Classes/"
exclude = [
    "docs",
    ".github",
    ".vscode",
    "mkdocs.yml"
]
private = true
realm = "shared"

[dependencies]